# Include this file inside http {} block:
#   include /path/to/nginx/upstreams.conf;

upstream up_ubuntu        { server archive.ubuntu.com:80;        keepalive 8; }
upstream up_ubuntu_ports  { server ports.ubuntu.com:80;          keepalive 4; }
upstream up_ubuntu_sec    { server security.ubuntu.com:80;       keepalive 4; }
upstream up_debian        { server deb.debian.org:80;            keepalive 8; }
upstream up_debian_sec    { server security.debian.org:80;       keepalive 4; }
upstream up_archlinux     { server mirrors.kernel.org:80;        keepalive 4; }
upstream up_fedora        { server dl.fedoraproject.org:80;      keepalive 4; }
upstream up_centos        { server mirror.stream.centos.org:80;  keepalive 4; }
upstream up_rocky         { server download.rockylinux.org:80;   keepalive 4; }
upstream up_alpine        { server dl-cdn.alpinelinux.org:80;    keepalive 4; }
upstream up_opensuse      { server download.opensuse.org:80;     keepalive 4; }
upstream up_kali          { server http.kali.org:80;             keepalive 4; }
upstream up_nixos         { server channels.nixos.org:80;        keepalive 4; }
upstream up_gentoo        { server distfiles.gentoo.org:80;      keepalive 4; }
